### ISSUE TITLE
Failed to read the figure or receiving `NotImplementedError`

### ISSUE THREAD

**Issue by Huang-CL** [ycwang-astro/vector-plot-extractor#1]
This could be a very useful project. Unfortunately, I couldn't get it to work for the following three figures I tested on my Ubuntu 22.04 system.
For the first attached figure (aa39344-20-fig9), the tool opens a blank window and couldn't catch any targets.
For the second attached figure (Borsa_VLT_slide_vertical), I received the following error message and couldn't open the first window.

```
Traceback (most recent call last):
  File "/home/huangcl/anaconda3/bin/vpextract", line 8, in <module>
    sys.exit(vpextract())
  File "/home/huangcl/anaconda3/lib/python3.10/site-packages/vpextractor/generalUI.py", line 112, in main
    runall(pdf_path=args.pdfpath)
  File "/home/huangcl/anaconda3/lib/python3.10/site-packages/vpextractor/generalUI.py", line 76, in runall
    ei = element_identifier(paths)
  File "/home/huangcl/anaconda3/lib/python3.10/site-packages/vpextractor/generalUI.py", line 28, in element_identifier
    artists, artists_in_plot, path_features = plot_paths(paths, ax=ax['main'])
  File "/home/huangcl/anaconda3/lib/python3.10/site-packages/vpextractor/drawing.py", line 153, in plot_paths
    item_type, coords, artist, path_feature = parse_path(path)
  File "/home/huangcl/anaconda3/lib/python3.10/site-packages/vpextractor/drawing.py", line 65, in parse_path
    raise NotImplementedError()
NotImplementedError
```

For the third attached figure (base75d_0.35ex_Tvr), after picking the black solid line and red dashed line and hitting finish, I received the following error message and could not proceed to the second step.
```
Traceback (most recent call last):
  File "/home/username/anaconda3/bin/vpextract", line 8, in <module>
    sys.exit(vpextract())
  File "/home/username/anaconda3/lib/python3.10/site-packages/vpextractor/generalUI.py", line 112, in main
    runall(pdf_path=args.pdfpath)
  File "/home/username/anaconda3/lib/python3.10/site-packages/vpextractor/generalUI.py", line 90, in runall
    objects = group_paths(paths, types, mode='typestr', markers=known_markers, marker_getter='mean')
  File "/home/username/anaconda3/lib/python3.10/site-packages/vpextractor/drawing.py", line 288, in group_paths
    'artist': PatchCollection(scatter_artists, match_original=True), # todo: what if user mark line as scatter? should disallow it!
  File "/home/username/anaconda3/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/home/username/anaconda3/lib/python3.10/site-packages/matplotlib/collections.py", line 1813, in __init__
    kwargs['facecolors'] = [determine_facecolor(p) for p in patches]
  File "/home/username/anaconda3/lib/python3.10/site-packages/matplotlib/collections.py", line 1813, in <listcomp>
    kwargs['facecolors'] = [determine_facecolor(p) for p in patches]
  File "/home/username/anaconda3/lib/python3.10/site-packages/matplotlib/collections.py", line 1809, in determine_facecolor
    if patch.get_fill():
AttributeError: 'Line2D' object has no attribute 'get_fill'. Did you mean: 'get_gid'?
```
[aa39344-20-fig9.pdf](https://github.com/ycwang-astro/vector-plot-extractor/files/14072405/aa39344-20-fig9.pdf)
[Borsa_VLT_slide_vertical.pdf](https://github.com/ycwang-astro/vector-plot-extractor/files/14072406/Borsa_VLT_slide_vertical.pdf)
[base75d_0.35ex_Tvr.pdf](https://github.com/ycwang-astro/vector-plot-extractor/files/14072409/base75d_0.35ex_Tvr.pdf)

**Comment by ycwang-astro** [comment]
Hi @Huang-CL, thanks for reporting!
- For the first figure (aa39344-20-fig9), this is a completely raster image, rather than a vector image. This project currently only handles vector images (or vector components in figures); for raster images, the underlying data is not included in the file, and one needs different algorithms to digitize it.  As a result, `vpextract` finds nothing to extract and shows a blank window. 
- For the second figure (Borsa_VLT_slide_vertical), some types of elements in the figure were not handled in the original version. I have fixed this, and you may try the latest development version before the next version is released:
  ```
  pip install git+https://github.com/ycwang-astro/vector-plot-extractor.git
  ```
  I have tested it on the second figure, and it seems to work normally now.
- For the third figure (base75d_0.35ex_Tvr), I cannot reproduce this error. If you have only hit the two lines and get this message,  it seems that you might have mislabeled the lines as "scatter" in the first step.

By the way, there seems to be errorbars in the second plot (Borsa_VLT_slide_vertical). Note that as a vector image, the errorbars and markers (the blue dots) are considered separate elements. Currently I do not implement higher-level detections of errorbars, so if you need the data of the errorbars, I would suggest:
- In the first step, click and handle the markers (filled blued dots) first (label them as "scatter");
- Then, click the remaining errorbars, label them as "lines", and match all errorbars with "color". They will be considered as a lot of lines.
- After going through the whole procedure and getting the exported data, you may want to match each scatter point with its errorbar by searching for "lines" with corresponding x, y coordinates.

I will consider improving detections of errorbars in the future.

**Comment by Huang-CL** [comment]
Thank you for the quick reply!
For the third figure, I did select "scatter" for the dashed line previously. After selecting the correct type, I retrieved the data from the third figure successfully.  I believe it would be helpful to further clarify that the dashed line is considered a "line" in the documentation.
For the second figure, I can open the figure using the new version. However, I figure it is even harder to select a target using the updated version.

**Comment by ycwang-astro** [comment]
Thank you for your suggestion! I will definitely consider improving the documentation and the UI.

For the second figure, it is still ok for me to select the data points and axis ticks. I am not sure if this is related to system/package versions, display settings, etc.  I think target selection is not changed in recent commits - but it is true that one has to make sure the mouse is on that object when selecting, at least for now.
